### ISSUE TITLE
rename repo?

### ISSUE THREAD

**Issue by serbinsh** [TESTgroup-BNL/spectratrait#77]
Should we just go ahead and rename this repo to the name of the R package it builds? The current name is a holdover from when this was just a repo of scripts.  It may make sense to just rename to "spectratrait" Thoughts?

@JulienLamour @regnans @neo0351 @DavidsonKen

**Comment by JulienLamour** [comment]
Yes I think it is sounding to rename it!

**Comment by serbinsh** [comment]
Yeah I agree.  also because we want the extracted zip files to also be consistent in naming and right now they are not.  I will rename the repo to match the R package name; "spectratrait". Fingers crossed

**Comment by regnans** [comment]
late to the party here, but yes, agree. And this is done, so I will close.
